server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/self_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  mvc: # 需要修改MVC的匹配策略，不然会不显示接口
    path match:
      matching-strategy: ant_path_matcher

  redis:
    host: localhost #redis 服务器地址
    database: 0 #redis数据库索引(默认是0)
    port: 6379 #redis服务器连接端口
    password:  #redis服务器连接密码(默认为空)
    jedis:
      pool:
        max-active: 8 #连接池最大连接数(使用负值表示没有限制)
        max-wait: -1ms #连接池最大阻塞等待时间(使用负值表示没有限制)
        max-idle: 8 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
    connect-timeout: 3000ms #连接超时时间(单位：毫秒)

redis: #自定义redis配置
  key:
    prefix:
      authCode: "portal:authCode"
    expire:
      time: 120


mybatis-plus: #设置mapper的路径和实体
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.itself.mall.pms.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用


# xxl-job配置
#xxl:
#  job:
#    admin:
#      # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；xxl-job后台管理界面的地址
#      addresses: http://127.0.0.1:8080/xxl-job-admin
#    executor:
#      # 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
#      address:
#      # 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
#      appname: test-job
#      # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
#      ip:
#      # 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
#      port: 0
#      # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
#      logpath: logs/xxl-job/test-job
#      # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
#      logretentiondays: 15
#    # 执行器通讯TOKEN [选填]：非空时启用；
#    accessToken: default_token




